services:
  pokeapp:
    build:
      context: .
    ports:
      - "8100:8100"
    volumes:
      - .:/app
      - /app/node_modules

  auth:
    build:
      context: ./auth-backend
    ports:
      - "4000:4000"
    volumes:
      - ./auth-backend:/app
      - /app/node_modules
    env_file:
      - ./auth-backend/.env.example

  # Descomente para fazer o build da imagem do backend (uso do webhook).
  # backend:
  #   build:
  #     context: ./backend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  #   command: node server.js
