services:
  pokeapp:
    build: .
    ports:
      - "8100:8100"
    volumes:
      - .:/app
      - /app/node_modules
    command: ionic serve --host 0.0.0.0 --port 8100

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: node server.js
